// Generated by `pnpm contracts:generate`. Do not edit by hand.

import { createKernelClient, type KernelClient, type KernelClientOptions } from "@agency_hub_core/contracts";

import { kernelOperations } from "./operations.ts";

export {
  KernelApiError,
  SDK_EXCLUDED_OPERATIONS,
  createKernelClient,
  type KernelClient,
  type KernelClientOptions,
  type KernelErrorCategory,
  type KernelOperationDef,
  type KernelOperationKey,
  type KernelOperationRequest,
  type KernelOperationResponse,
  type KernelSdkMethodKey,
} from "@agency_hub_core/contracts";
// Runtime surface for out-of-workspace consumers (Stage 24: client repos
// cannot reach @agency_hub_core/contracts the way the dashboard does).
export {
  decodeDomainEventCursor,
  fetchVoiceNoteAudio,
  // Shared client-side predicate (coach-chat spec §8): apply to a terminal
  // stop reason before committing a coach answer / attaching a recap.
  isOutputExhausted,
  ofapiRead,
  routeSchemas,
  streamAiFeature,
  streamAiGateway,
  subscribeDomainEvents,
  subscribeSyncEvents,
  // The feature lane's frames are a SUPERSET of the raw gateway's (#140
  // debug echo): a client handling streamAiFeature must widen to
  // AiFeatureStreamFrame, not AiGatewayStreamFrame.
  type AiFeatureDebugInputFrame,
  type AiFeatureStreamFrame,
  type AiGatewayStreamFrame,
  type DomainEventFrame,
  type DomainEventsSnapshotRequired,
  type KernelStreamHandle,
  type SyncEvent,
  type SyncSnapshotRequired,
} from "@agency_hub_core/contracts";
export { kernelOperations } from "./operations.ts";
export { KERNEL_CONTRACT_HASH, KERNEL_SDK_VERSION } from "./meta.ts";
// The chat extension's known values (routes-client.ts). On the wire these
// vocabularies are open strings; the client narrows to these constants and
// reads an unknown member as off / unknown.
export {
  CLIENT_FEATURE_FLAG_NAMES,
  CLIENT_FEATURE_UNAVAILABLE_REASONS,
  CLIENT_HUB_CAPABILITY_NAMES,
  CLIENT_KNOWN_PLATFORMS,
  CLIENT_KNOWN_ROLES,
  CLIENT_NUMERIC_ID_PATTERN,
  type ClientFeatureFlagName,
  type ClientFeatureUnavailableReason,
  type ClientHubCapabilityName,
} from "@agency_hub_core/contracts";

export function createClient(options: KernelClientOptions): KernelClient {
  return createKernelClient(kernelOperations, options);
}
