// Generated by `pnpm contracts:generate`. Do not edit by hand.

import { createKernelClient, type KernelClient, type KernelClientOptions } from "@agency_hub_core/contracts";

import { kernelOperations } from "./operations.ts";

export {
  KernelApiError,
  SDK_EXCLUDED_OPERATIONS,
  createKernelClient,
  type KernelClient,
  type KernelClientOptions,
  type KernelErrorCategory,
  type KernelOperationDef,
  type KernelOperationKey,
  type KernelOperationRequest,
  type KernelOperationResponse,
  type KernelSdkMethodKey,
} from "@agency_hub_core/contracts";
// Runtime surface for out-of-workspace consumers (Stage 24: client repos
// cannot reach @agency_hub_core/contracts the way the dashboard does).
export {
  decodeDomainEventCursor,
  ofapiRead,
  routeSchemas,
  streamAiFeature,
  streamAiGateway,
  subscribeDomainEvents,
  subscribeSyncEvents,
  type AiGatewayStreamFrame,
  type DomainEventFrame,
  type DomainEventsSnapshotRequired,
  type KernelStreamHandle,
  type SyncEvent,
  type SyncSnapshotRequired,
} from "@agency_hub_core/contracts";
export { kernelOperations } from "./operations.ts";
export { KERNEL_CONTRACT_HASH, KERNEL_SDK_VERSION } from "./meta.ts";

export function createClient(options: KernelClientOptions): KernelClient {
  return createKernelClient(kernelOperations, options);
}
