// Generated by `pnpm contracts:generate`. Do not edit by hand.

/** sha256 over the normalized OpenAPI document — the cross-repo drift key. */
export const KERNEL_CONTRACT_HASH = "7408ef8c284b4c6b27ce82fea153f4d1a867d6b01ce9673a753cecea092f5c66";
export const KERNEL_SDK_VERSION = "0.1.0";
