// Generated by `pnpm contracts:generate`. Do not edit by hand.

/** sha256 over the normalized OpenAPI document — the cross-repo drift key. */
export const KERNEL_CONTRACT_HASH = "f632ba17457e4c76178eb80c836af89741e6b6acf1641ccb38ddd16a9e6b21eb";
export const KERNEL_SDK_VERSION = "0.1.0";
