// Generated by `pnpm contracts:generate`. Do not edit by hand.

/** sha256 over the normalized OpenAPI document — the cross-repo drift key. */
export const KERNEL_CONTRACT_HASH = "c67412d0af2824e15c2c2c52e82677844318d3c6f3bfdacb83708d98b184d110";
export const KERNEL_SDK_VERSION = "0.1.0";
