import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

// Blocker 2 (coach-chat spec §8): the isOutputExhausted predicate must be
// reachable by out-of-workspace consumers (the extension) from @kernel/sdk so
// they can apply it client-side. That reachability is a chain of four files;
// each link is a repo invariant guarded here so a future edit can't silently
// break the export the way the original staging list did.
describe("vendored SDK surfaces the ai-stop-reason predicate", () => {
  it("stages ai-stop-reason.ts into the vendored shared subset", async () => {
    const script = await readFile("scripts/vendor-sdk.mjs", "utf8");
    // The staging array the compiler bundles from packages/shared.
    expect(script).toContain('"spender-retention.ts", "ai-stop-reason.ts"');
    // The generated shared barrel that re-exports the staged modules.
    expect(script).toContain('export * from "./ai-stop-reason";');
  });

  it("stages EVERY module the contracts barrel re-exports", async () => {
    // Derived, not hand-listed. The fixed staging list has now silently
    // diverged from the barrel twice, and each time the symptom was a TS2307
    // during a CLIENT re-vendor — far from the edit that caused it. Reading the
    // barrel here turns "added an export, forgot the staging list" into a CI
    // failure in the same change.
    const [script, contractsIndex] = await Promise.all([
      readFile("scripts/vendor-sdk.mjs", "utf8"),
      readFile("packages/contracts/src/index.ts", "utf8"),
    ]);

    const reExported = [...contractsIndex.matchAll(/export \* from "\.\/([\w.-]+)";/g)]
      .map((match) => match[1]!);
    expect(reExported.length).toBeGreaterThan(0);

    const missing = reExported.filter((file) => !script.includes(`"${file}"`));
    expect(missing, "contracts barrel modules missing from the vendor staging list").toEqual([]);
    // Spot-pin the Agent Read Plane trio so the derivation itself cannot rot.
    expect(reExported).toEqual(expect.arrayContaining([
      "agent-read-registry.ts",
      "agent-read-capabilities.ts",
      "agent-read-datasets.ts",
    ]));
  });

  it("stages transitive contract imports reached through the public barrel", async () => {
    const script = await readFile("scripts/vendor-sdk.mjs", "utf8");
    const required = new Set<string>();
    const pending = ["index.ts"];
    while (pending.length > 0) {
      const file = pending.pop()!;
      if (required.has(file)) continue;
      required.add(file);
      const source = await readFile(`packages/contracts/src/${file}`, "utf8");
      for (const match of source.matchAll(/from ["']\.\/([\w.-]+\.ts)["']/g)) {
        pending.push(match[1]!);
      }
    }
    // routes.ts reaches this schema without re-exporting it from index.ts.
    expect(required.has("routes-ofapi-marketing.ts")).toBe(true);
    const missing = [...required].filter(file => !script.includes(`"${file}"`));
    expect(missing, "transitive contract imports missing from vendor staging").toEqual([]);
  });

  it("re-exports isOutputExhausted through the contracts barrel", async () => {
    const contractsIndex = await readFile("packages/contracts/src/index.ts", "utf8");
    expect(contractsIndex).toContain(
      'export { isOutputExhausted } from "@agency_hub_core/shared";',
    );
  });

  it("keeps isOutputExhausted on the generated @kernel/sdk surface", async () => {
    // Generated by pnpm contracts:generate; the generator (generate-sdk.ts)
    // names it in the runtime-surface export block, so a regen preserves it.
    const sdkIndex = await readFile("packages/sdk/src/index.ts", "utf8");
    expect(sdkIndex).toContain("isOutputExhausted,");
  });
});
