import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

// Blocker 2 (coach-chat spec §8): the isOutputExhausted predicate must be
// reachable by out-of-workspace consumers (the extension) from @kernel/sdk so
// they can apply it client-side. That reachability is a chain of four files;
// each link is a repo invariant guarded here so a future edit can't silently
// break the export the way the original staging list did.
describe("vendored SDK surfaces the ai-stop-reason predicate", () => {
  it("stages ai-stop-reason.ts into the vendored shared subset", async () => {
    const script = await readFile("scripts/vendor-sdk.mjs", "utf8");
    // The staging array the compiler bundles from packages/shared.
    expect(script).toContain('"spender-retention.ts", "ai-stop-reason.ts"');
    // Every module the contracts barrel re-exports must be staged, or the
    // vendor compile dies with TS2307 and no client can re-vendor. This is the
    // second time the fixed staging list silently diverged from the barrel.
    expect(script).toContain('"agent-read-registry.ts"');
    // The generated shared barrel that re-exports the staged modules.
    expect(script).toContain('export * from "./ai-stop-reason";');
  });

  it("re-exports isOutputExhausted through the contracts barrel", async () => {
    const contractsIndex = await readFile("packages/contracts/src/index.ts", "utf8");
    expect(contractsIndex).toContain(
      'export { isOutputExhausted } from "@agency_hub_core/shared";',
    );
  });

  it("keeps isOutputExhausted on the generated @kernel/sdk surface", async () => {
    // Generated by pnpm contracts:generate; the generator (generate-sdk.ts)
    // names it in the runtime-surface export block, so a regen preserves it.
    const sdkIndex = await readFile("packages/sdk/src/index.ts", "utf8");
    expect(sdkIndex).toContain("isOutputExhausted,");
  });
});
