import { CLIENT_TOKEN_PROFILES, clientTokenAllowlistApplies, clientTokenProfileAllows } from "./client-token-scopes.ts";
import type { RouteAuthPolicy } from "./routes.ts";

// Kernel Stage 19: the generated authorization-policy document. Rendered by
// `pnpm contracts:generate` from the API server's route policy table (route →
// declared auth), so "who can call what" is one greppable page instead of 132
// handler bodies.

export interface AuthorizationPolicyRow {
  method: string;
  url: string;
  routeKey: string;
  auth: RouteAuthPolicy | null;
}

const KIND_DESCRIPTIONS: Record<RouteAuthPolicy["kind"], string> = {
  "public": "no principal required",
  "hmac": "HMAC signature over the raw body (in-handler)",
  "monitoring": "x-monitoring-token OR dashboard session",
  "session": "dashboard cookie session (owner/team_lead)",
  "any-session": "any live cookie session, any human role",
  "owner-session": "dashboard cookie session, owner role only",
  "apiKey": "device-token bearer (historical kind name: Decision 370 retired API keys)",
  "device-token": "device-token bearer only",
  "pending-device-token": "short-lived pending device-token bearer, activation route only",
  "agentKey": "Agent Read Plane key only; no human principal is admitted",
  "any": "any authenticated principal except an agent key",
};

/** The narrow-token column: "yes" on the profile's list, "no" (403) off it,
 *  "—" where the route takes no principal at all. */
function clientTokenCell(row: AuthorizationPolicyRow): string {
  if (!row.auth || !clientTokenAllowlistApplies(row.auth)) {
    return "—";
  }
  return clientTokenProfileAllows("chat-extension", row.routeKey) ? "yes" : "no";
}

export function renderAuthorizationPolicyMarkdown(rows: readonly AuthorizationPolicyRow[]): string {
  const sorted = [...rows].sort((left, right) =>
    left.url === right.url ? left.method.localeCompare(right.method) : left.url.localeCompare(right.url),
  );

  const lines: string[] = [
    "<!-- Generated by `pnpm contracts:generate`. Do not edit by hand. -->",
    "",
    "# Authorization policy",
    "",
    "Every route's declared `auth` policy, enforced by the API server's",
    "authorization middleware (`AUTH_POLICY_ENFORCEMENT=log|enforce`).",
    "`scope: page` means the middleware resolves the `:pageLabel` path param and",
    "requires page access before the handler runs; page ids derived from query or",
    "body remain handler-checked and are noted per route in the service layer.",
    "",
    "| Kind | Meaning |",
    "| --- | --- |",
    ...Object.entries(KIND_DESCRIPTIONS).map(([kind, meaning]) => `| \`${kind}\` | ${meaning} |`),
    "",
    "The `chat-extension token` column is the narrow device token a client asks",
    "for at password sign-in (`client: \"chat-extension\"`): it reaches only the",
    `${CLIENT_TOKEN_PROFILES["chat-extension"].operations.length} routes marked "yes", and every route marked "no" refuses it with 403 in`,
    "both enforcement modes. A full device token is not affected.",
    "",
    `## Routes (${sorted.length})`,
    "",
    "| Method | Path | Route key | Kind | Roles | Page scope | chat-extension token |",
    "| --- | --- | --- | --- | --- | --- | --- |",
  ];

  for (const row of sorted) {
    const auth = row.auth;
    lines.push([
      "",
      row.method,
      `\`${row.url}\``,
      `\`${row.routeKey}\``,
      auth ? `\`${auth.kind}\`` : "**UNDECLARED**",
      auth?.roles?.length ? auth.roles.join(", ") : "—",
      auth?.scope === "page" ? "page" : "—",
      clientTokenCell(row),
      "",
    ].join(" | ").trim());
  }

  lines.push("");
  return lines.join("\n");
}
