// Generated by `pnpm contracts:generate`. Do not edit by hand.

/** sha256 over the normalized OpenAPI document actually served by this build. */
export const KERNEL_CONTRACT_HASH = "5687c9bccc4ae031fd75bdfd069daea330033eece9ab91ad4809eda64c7b3ef2";
