// Generated by `pnpm contracts:generate`. Do not edit by hand.

/** sha256 over the normalized OpenAPI document actually served by this build. */
export const KERNEL_CONTRACT_HASH = "c00d0f1c391d6315f05b0edb682bb78b1d611c51dcdf9cdd4eba618d55db9a7b";
