// Generated by `pnpm contracts:generate`. Do not edit by hand.

/** sha256 over the normalized OpenAPI document actually served by this build. */
export const KERNEL_CONTRACT_HASH = "46a08347cfc74ebbd6c80fd62803e0cc4b85442a944f24a9592347562ca942bb";
