import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { createLogger } from "@agency_hub_core/shared";

import { buildApiServer, normalizeOpenApiDocument } from "../../../apps/runtime/src/api/server.ts";
import { renderAuthorizationPolicyMarkdown } from "./authorization-policy.ts";
import { buildSdkFiles, computeContractHash } from "./generate-sdk.ts";

async function main() {
  const encryptionKey = Buffer.alloc(32, 0);
  const server = await buildApiServer({
    config: {
      databaseUrl: "",
      encryptionKey,
      encryptionKeyVersion: 1,
      encryptionKeysByVersion: new Map([[1, encryptionKey]]),
      logLevel: "silent",
      apiHost: "0.0.0.0",
      apiPort: 3000,
      trustProxy: false,
      isProduction: false,
      sessionTtlDays: 30,
      fanslyBaseUrl: "https://apiv3.fansly.com/api/v1",
      syncHttpTraceFile: null,
      fanslyDefaultDelayMs: 2500,
      fanslyDmConversationsDelayMs: 5000,
      fanslyDmMessagesDelayMs: 5000,
      followerPageDelayMs: 5000,
      onlyFansDefaultDelayMs: 1000,
      transactionLookbackDays: 7,
      transactionRescanCapDays: 30,
      syncSharedRateLimitEnabled: false,
      egressPacerMode: "off" as const,
      lakeDir: "lake",
      syncPageExecutorConcurrency: 1,
      syncObservabilityRetentionDays: 30,
      healthSyncLightMaxAgeMinutes: 180,
      healthSyncFollowerMaxAgeMinutes: 1080,
      healthSyncMonitoringToken: null,
      telegramBotToken: null,
      telegramChatId: null,
      telegramEnabled: false,
      telegramReportHourUtc: 9,
      serviceEgressProxyUrl: null,
      serviceEgressProxyUsername: null,
      serviceEgressProxyPassword: null,
    },
    logger: createLogger("silent"),
    pool: {} as never,
    db: {} as never,
    async close() {},
  });

  try {
    await server.ready();
    const spec = normalizeOpenApiDocument(server.swagger() as unknown as Record<string, unknown>);
    const openApiDocumentJson = `${JSON.stringify(spec, null, 2)}\n`;
    const openapiPath = path.resolve("reference/agency-hub.openapi.json");
    await writeFile(openapiPath, openApiDocumentJson, "utf8");

    const contractHash = computeContractHash(openApiDocumentJson);
    await writeFile(
      path.resolve("packages/contracts/src/contract-hash.ts"),
      "// Generated by `pnpm contracts:generate`. Do not edit by hand.\n\n"
        + "/** sha256 over the normalized OpenAPI document actually served by this build. */\n"
        + `export const KERNEL_CONTRACT_HASH = ${JSON.stringify(contractHash)};\n`,
      "utf8",
    );

    // Kernel Stage 19: the authorization-policy table, from the same server boot
    // (route registrations carry the declared auth policies).
    const policyPath = path.resolve("docs/generated/authorization-policy.md");
    await mkdir(path.dirname(policyPath), { recursive: true });
    await writeFile(policyPath, renderAuthorizationPolicyMarkdown(server.routePolicyTable), "utf8");

    // Kernel Stage 20: the generated-only @kernel/sdk package (operations
    // manifest + contract hash + re-exports; runtime lives in this package).
    const sdkFiles = buildSdkFiles({
      routePolicyTable: server.routePolicyTable,
      openApiDocumentJson,
      sdkVersion: "0.4.0",
    });
    for (const [relativePath, content] of sdkFiles) {
      const target = path.resolve("packages/sdk", relativePath);
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, content, "utf8");
    }
  } finally {
    await server.close();
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
