import { createHash } from "node:crypto";

import { routeSchemas } from "./routes.ts";

// Kernel Stage 20: emits the generated-only @kernel/sdk package. The moving
// parts (client, validation, error taxonomy) live in the contracts package's
// sdk-runtime; what gets generated is the operations manifest (method/path per
// registry key, recovered from the booted server's route table), the contract
// hash, and thin re-exports. Pure function of its inputs — determinism is a
// tested property (two runs must be byte-identical).

export interface SdkRouteRow {
  method: string;
  url: string;
  routeKey: string;
}

export interface SdkGenerationInput {
  routePolicyTable: readonly SdkRouteRow[];
  /** The exact bytes written to reference/agency-hub.openapi.json. */
  openApiDocumentJson: string;
  sdkVersion: string;
}

const BANNER = "// Generated by `pnpm contracts:generate`. Do not edit by hand.";

export function computeContractHash(openApiDocumentJson: string): string {
  return createHash("sha256").update(openApiDocumentJson, "utf8").digest("hex");
}

export function buildSdkFiles(input: SdkGenerationInput): Map<string, string> {
  const keys = Object.keys(routeSchemas).sort();
  const byKey = new Map<string, SdkRouteRow>();
  for (const row of input.routePolicyTable) {
    if (byKey.has(row.routeKey)) {
      throw new Error(`SDK generator: route key registered twice: ${row.routeKey}`);
    }
    byKey.set(row.routeKey, row);
  }
  const missing = keys.filter((key) => !byKey.has(key));
  const unknown = [...byKey.keys()].filter((key) => !(key in routeSchemas));
  if (missing.length > 0 || unknown.length > 0) {
    throw new Error(
      `SDK generator: manifest/registry mismatch — missing: [${missing.join(", ")}], unknown: [${unknown.join(", ")}]`,
    );
  }

  // The hash covers the full normalized OpenAPI document, so any schema-shape
  // change (a renamed response field, a new required param) changes it — the
  // cross-repo drift gates key off exactly this value.
  const contractHash = computeContractHash(input.openApiDocumentJson);

  const operationsTs = [
    BANNER,
    "",
    'import type { KernelOperationDef, KernelOperationKey } from "@agency_hub_core/contracts";',
    "",
    "export const kernelOperations = {",
    ...keys.map((key) => {
      const row = byKey.get(key)!;
      return `  ${key}: { method: ${JSON.stringify(row.method)}, path: ${JSON.stringify(row.url)} },`;
    }),
    "} as const satisfies Record<KernelOperationKey, KernelOperationDef>;",
    "",
  ].join("\n");

  const metaTs = [
    BANNER,
    "",
    "/** sha256 over the normalized OpenAPI document — the cross-repo drift key. */",
    `export const KERNEL_CONTRACT_HASH = ${JSON.stringify(contractHash)};`,
    `export const KERNEL_SDK_VERSION = ${JSON.stringify(input.sdkVersion)};`,
    "",
  ].join("\n");

  const indexTs = [
    BANNER,
    "",
    'import { createKernelClient, type KernelClient, type KernelClientOptions } from "@agency_hub_core/contracts";',
    "",
    'import { kernelOperations } from "./operations.ts";',
    "",
    "export {",
    "  KernelApiError,",
    "  SDK_EXCLUDED_OPERATIONS,",
    "  createKernelClient,",
    "  type KernelClient,",
    "  type KernelClientOptions,",
    "  type KernelErrorCategory,",
    "  type KernelOperationDef,",
    "  type KernelOperationKey,",
    "  type KernelOperationRequest,",
    "  type KernelOperationResponse,",
    "  type KernelSdkMethodKey,",
    '} from "@agency_hub_core/contracts";',
    "// Runtime surface for out-of-workspace consumers (Stage 24: client repos",
    "// cannot reach @agency_hub_core/contracts the way the dashboard does).",
    "export {",
    "  decodeDomainEventCursor,",
    "  fetchVoiceNoteAudio,",
    "  // Shared client-side predicate (coach-chat spec §8): apply to a terminal",
    "  // stop reason before committing a coach answer / attaching a recap.",
    "  isOutputExhausted,",
    "  ofapiRead,",
    "  routeSchemas,",
    "  streamAiFeature,",
    "  streamAiGateway,",
    "  subscribeDomainEvents,",
    "  subscribeSyncEvents,",
    "  // The feature lane's frames are a SUPERSET of the raw gateway's (#140",
    "  // debug echo): a client handling streamAiFeature must widen to",
    "  // AiFeatureStreamFrame, not AiGatewayStreamFrame.",
    "  type AiFeatureDebugInputFrame,",
    "  type AiFeatureStreamFrame,",
    "  type AiGatewayStreamFrame,",
    "  type DomainEventFrame,",
    "  type DomainEventsSnapshotRequired,",
    "  type KernelStreamHandle,",
    "  type SyncEvent,",
    "  type SyncSnapshotRequired,",
    '} from "@agency_hub_core/contracts";',
    'export { kernelOperations } from "./operations.ts";',
    'export { KERNEL_CONTRACT_HASH, KERNEL_SDK_VERSION } from "./meta.ts";',
    "",
    "export function createClient(options: KernelClientOptions): KernelClient {",
    "  return createKernelClient(kernelOperations, options);",
    "}",
    "",
  ].join("\n");

  const packageJson = `${JSON.stringify(
    {
      name: "@kernel/sdk",
      version: input.sdkVersion,
      description: "Generated kernel API client. Do not edit by hand — regenerate with `pnpm contracts:generate`.",
      type: "module",
      exports: { ".": "./src/index.ts" },
      dependencies: {
        "@agency_hub_core/contracts": "workspace:*",
        "zod": "^4.1.5",
      },
    },
    null,
    2,
  )}\n`;

  const readme = [
    "<!-- Generated by `pnpm contracts:generate`. Do not edit by hand. -->",
    "",
    "# @kernel/sdk",
    "",
    "Generated, typed client for the kernel API. Every operation is named after",
    "its `routeSchemas` key; request/response types and runtime validation come",
    "straight from the Zod contracts, so this package cannot drift from what the",
    "server enforces.",
    "",
    "```ts",
    'import { createClient } from "@kernel/sdk";',
    "",
    'const client = createClient({ baseUrl: "", auth: { mode: "cookie" } });',
    'const me = await client.me();                       // typed + runtime-validated',
    'const revenue = await client.pageRevenue({ params: { pageLabel: "lana" }, query: { period: "7d" } });',
    "```",
    "",
    "## How the SDK is versioned and pinned (DP 10, owner-confirmed)",
    "",
    "Distribution is **git-tag installs** — no npm registry:",
    "",
    "```jsonc",
    '// consumer package.json',
    '"@kernel/sdk": "github:<org>/core#sdk-vX.Y.Z"',
    "```",
    "",
    "- `KERNEL_CONTRACT_HASH` (in `meta.ts`) is a sha256 over the normalized",
    "  OpenAPI document. Consumer CI compares its pinned hash against",
    "  core@main's published hash; a mismatch is contract drift and fails the",
    "  build.",
    "- `sdk-vX.Y.Z` tags are published by the core release step; a scheduled",
    "  bump-PR updates each consumer's pin.",
    "- Everything in this package is machine-generated. Fix things in",
    "  `packages/contracts` (runtime: `src/sdk-runtime.ts`; generator:",
    "  `src/generate-sdk.ts`) and regenerate.",
    "",
  ].join("\n");

  return new Map([
    ["package.json", packageJson],
    ["README.md", readme],
    ["src/operations.ts", operationsTs],
    ["src/meta.ts", metaTs],
    ["src/index.ts", indexTs],
  ]);
}
