import { createHash } from "node:crypto";

import { routeSchemas } from "./routes.ts";

// Kernel Stage 20: emits the generated-only @kernel/sdk package. The moving
// parts (client, validation, error taxonomy) live in the contracts package's
// sdk-runtime; what gets generated is the operations manifest (method/path per
// registry key, recovered from the booted server's route table), the contract
// hash, and thin re-exports. Pure function of its inputs — determinism is a
// tested property (two runs must be byte-identical).

export interface SdkRouteRow {
  method: string;
  url: string;
  routeKey: string;
}

export interface SdkGenerationInput {
  routePolicyTable: readonly SdkRouteRow[];
  /** The exact bytes written to reference/agency-hub.openapi.json. */
  openApiDocumentJson: string;
  sdkVersion: string;
}

const BANNER = "// Generated by `pnpm contracts:generate`. Do not edit by hand.";

export function computeContractHash(openApiDocumentJson: string): string {
  return createHash("sha256").update(openApiDocumentJson, "utf8").digest("hex");
}

export function buildSdkFiles(input: SdkGenerationInput): Map<string, string> {
  const keys = Object.keys(routeSchemas).sort();
  const byKey = new Map<string, SdkRouteRow>();
  for (const row of input.routePolicyTable) {
    if (byKey.has(row.routeKey)) {
      throw new Error(`SDK generator: route key registered twice: ${row.routeKey}`);
    }
    byKey.set(row.routeKey, row);
  }
  const missing = keys.filter((key) => !byKey.has(key));
  const unknown = [...byKey.keys()].filter((key) => !(key in routeSchemas));
  if (missing.length > 0 || unknown.length > 0) {
    throw new Error(
      `SDK generator: manifest/registry mismatch — missing: [${missing.join(", ")}], unknown: [${unknown.join(", ")}]`,
    );
  }

  // The hash covers the full normalized OpenAPI document, so any schema-shape
  // change (a renamed response field, a new required param) changes it — the
  // cross-repo drift gates key off exactly this value.
  const contractHash = computeContractHash(input.openApiDocumentJson);

  const operationsTs = [
    BANNER,
    "",
    'import type { KernelOperationDef, KernelOperationKey } from "@agency_hub_core/contracts";',
    "",
    "export const kernelOperations = {",
    ...keys.map((key) => {
      const row = byKey.get(key)!;
      return `  ${key}: { method: ${JSON.stringify(row.method)}, path: ${JSON.stringify(row.url)} },`;
    }),
    "} as const satisfies Record<KernelOperationKey, KernelOperationDef>;",
    "",
  ].join("\n");

  const metaTs = [
    BANNER,
    "",
    "/** sha256 over the normalized OpenAPI document — the cross-repo drift key. */",
    `export const KERNEL_CONTRACT_HASH = ${JSON.stringify(contractHash)};`,
    `export const KERNEL_SDK_VERSION = ${JSON.stringify(input.sdkVersion)};`,
    "",
  ].join("\n");

  const indexTs = [
    BANNER,
    "",
    'import { createKernelClient, type KernelClient, type KernelClientOptions } from "@agency_hub_core/contracts";',
    "",
    'import { kernelOperations } from "./operations.ts";',
    "",
    "export {",
    "  KernelApiError,",
    "  SDK_EXCLUDED_OPERATIONS,",
    "  createKernelClient,",
    "  type KernelClient,",
    "  type KernelClientOptions,",
    "  type KernelErrorCategory,",
    "  type KernelOperationDef,",
    "  type KernelOperationKey,",
    "  type KernelOperationRequest,",
    "  type KernelOperationResponse,",
    "  type KernelSdkMethodKey,",
    '} from "@agency_hub_core/contracts";',
    "// Runtime surface for out-of-workspace consumers (Stage 24: client repos",
    "// cannot reach @agency_hub_core/contracts the way the dashboard does).",
    "export {",
    "  // The tokens streamAiFeature may advertise (`capabilities` option).",
    "  AI_STREAM_CAPABILITIES,",
    "  decodeDomainEventCursor,",
    "  fetchVoiceNoteAudio,",
    "  // Shared client-side predicate (coach-chat spec §8): apply to a terminal",
    "  // stop reason before committing a coach answer / attaching a recap.",
    "  isOutputExhausted,",
    "  ofapiRead,",
    "  routeSchemas,",
    "  streamAiFeature,",
    "  streamAiGateway,",
    "  subscribeDomainEvents,",
    "  subscribeSyncEvents,",
    "  // The feature lane's frames are a SUPERSET of the raw gateway's (#140",
    "  // debug echo): a client handling streamAiFeature must widen to",
    "  // AiFeatureStreamFrame, not AiGatewayStreamFrame.",
    "  type AiFeatureContextFrame,",
    "  type AiFeatureDebugInputFrame,",
    "  type AiFeatureStreamFrame,",
    "  type AiGatewayStreamFrame,",
    "  type AiStreamCapability,",
    "  type DomainEventFrame,",
    "  type DomainEventsSnapshotRequired,",
    "  type KernelStreamHandle,",
    "  type SyncEvent,",
    "  type SyncSnapshotRequired,",
    '} from "@agency_hub_core/contracts";',
    'export { kernelOperations } from "./operations.ts";',
    'export { KERNEL_CONTRACT_HASH, KERNEL_SDK_VERSION } from "./meta.ts";',
    "// The chat extension's known values (routes-client.ts). On the wire these",
    "// vocabularies are open strings; the client narrows to these constants and",
    "// reads an unknown member as off / unknown.",
    "export {",
    "  CLIENT_COVERAGE_LEVELS,",
    "  CLIENT_FEATURE_FLAG_NAMES,",
    "  CLIENT_FEATURE_UNAVAILABLE_REASONS,",
    "  CLIENT_GENERATION_NOT_ELIGIBLE_REASONS,",
    "  CLIENT_HUB_CAPABILITY_NAMES,",
    "  CLIENT_KNOWN_PLATFORMS,",
    "  CLIENT_KNOWN_ROLES,",
    "  CLIENT_NUMERIC_ID_PATTERN,",
    "  CLIENT_RECAP_TRANSCRIPT_COVERAGES,",
    "  type ClientCoverageLevel,",
    "  type ClientFeatureFlagName,",
    "  type ClientFeatureUnavailableReason,",
    "  type ClientGenerationNotEligibleReason,",
    "  type ClientHubCapabilityName,",
    "  type ClientRecapTranscriptCoverage,",
    '} from "@agency_hub_core/contracts";',
    "// The AI context frame's known values (routes.ts, `context_v1`): its open",
    "// tokens narrow to these, and `knownFanMessageIds` takes at most the MAX.",
    "// AI_LIVE_TEXT_*: the caps of the body's `liveTextContext` (fresh text).",
    "export {",
    "  AI_CONTEXT_LIVE_STATUSES,",
    "  AI_CONTEXT_SOURCES,",
    "  AI_FAN_LANGUAGE_EVIDENCE,",
    "  AI_KNOWN_FAN_MESSAGE_IDS_MAX,",
    "  AI_KNOWN_FAN_MESSAGE_STATES,",
    "  AI_LIVE_TEXT_MAX_CHARS,",
    "  AI_LIVE_TEXT_MAX_ITEMS,",
    '} from "@agency_hub_core/contracts";',
    "// The chat extension's health report (routes-client.ts). No route carries it:",
    "// it rides one ingest batch of its own once the bootstrap lists",
    "// client-health-perf-v1, and its histograms use these fixed bucket bounds.",
    "export {",
    "  CLIENT_HEALTH_CODE_PATTERN,",
    "  CLIENT_HEALTH_INGEST_KIND,",
    "  CLIENT_HEALTH_PERF_METRICS,",
    "  clientHealthPerfHistogramSchema,",
    "  clientHealthReportV1Schema,",
    "  type ClientHealthPerfHistogram,",
    "  type ClientHealthPerfMetricName,",
    "  type ClientHealthReportV1,",
    '} from "@agency_hub_core/contracts";',
    "// The caller's own AI spend (routes-client.ts, clientAiUsageDaily): its",
    "// limits and the known values of its open tokens and refusal reasons.",
    "export {",
    "  CLIENT_AI_USAGE_COVERAGE,",
    "  CLIENT_AI_USAGE_COVERAGE_REASONS,",
    "  CLIENT_AI_USAGE_MAX_AGE_DAYS,",
    "  CLIENT_AI_USAGE_MAX_DAYS,",
    "  CLIENT_AI_USAGE_REFUSAL_REASONS,",
    "  type ClientAiUsageCoverage,",
    "  type ClientAiUsageCoverageReason,",
    "  type ClientAiUsageRefusalReason,",
    '} from "@agency_hub_core/contracts";',
    "// The Spenders statistics (routes-client.ts, clientSpenderStats): the one",
    "// window it serves and the known values of its open tokens and refusal reason.",
    "export {",
    "  CLIENT_SPENDER_STATS_COVERAGE_REASONS,",
    "  CLIENT_SPENDER_STATS_REFUSAL_REASONS,",
    "  CLIENT_SPENDER_STATS_REMAINDER_TIER_KEYS,",
    "  CLIENT_SPENDER_STATS_WINDOW_DAYS,",
    "  type ClientSpenderStatsCoverageReason,",
    "  type ClientSpenderStatsRefusalReason,",
    '} from "@agency_hub_core/contracts";',
    "// The awaiting-reply queue (routes-client.ts, clientSpenderAwaitingReply): its",
    "// limits, the known values of `readState`, and the refusal reason of a cursor.",
    "export {",
    "  CLIENT_CURSOR_REFUSAL_REASONS,",
    "  CLIENT_SPENDER_AWAITING_REPLY_DEFAULT_LIMIT,",
    "  CLIENT_SPENDER_AWAITING_REPLY_MAX_LIMIT,",
    "  CLIENT_SPENDER_AWAITING_REPLY_READ_STATES,",
    "  type ClientCursorRefusalReason,",
    "  type ClientSpenderAwaitingReplyReadState,",
    '} from "@agency_hub_core/contracts";',
    "// The archive feed (routes-client.ts, clientConversationFeed): its limits",
    "// and the known values of its open tokens.",
    "export {",
    "  CLIENT_FEED_DEFAULT_LIMIT,",
    "  CLIENT_FEED_MAX_LIMIT,",
    "  CLIENT_FEED_PING_SEGMENTS,",
    "  CLIENT_FEED_SENDERS,",
    "  CLIENT_FEED_SOURCES,",
    "  CLIENT_FEED_SUMMARY_WINDOW_DEFAULT,",
    "  CLIENT_FEED_SUMMARY_WINDOW_MAX,",
    "  CLIENT_FEED_SUMMARY_WINDOW_MIN,",
    "  type ClientFeedPingSegment,",
    "  type ClientFeedSender,",
    "  type ClientFeedSource,",
    '} from "@agency_hub_core/contracts";',
    "// The greeting lease and send custody (routes-client.ts, clientFanClaim): the",
    "// states of its three automata, closed on the wire, and the known values of",
    "// its open tokens (the greeting's source; the purpose and state of a",
    "// resolved send).",
    "export {",
    "  CLIENT_CLAIM_ACTIONS,",
    "  CLIENT_CLAIM_MAX_PARTS,",
    "  CLIENT_CLAIM_MAX_VARIANTS,",
    "  CLIENT_CUSTODY_STATES,",
    "  CLIENT_GREETING_SOURCES,",
    "  CLIENT_GREETING_STATES,",
    "  CLIENT_LEASE_HOLDERS,",
    "  CLIENT_LEASE_STATES,",
    "  CLIENT_SEND_FAILURE_REASONS,",
    "  CLIENT_SEND_PURPOSES,",
    "  type ClientClaimAction,",
    "  type ClientCustodyState,",
    "  type ClientGreetingSource,",
    "  type ClientSendPurpose,",
    '} from "@agency_hub_core/contracts";',
    "// The narrow token's profiles (client-token-scopes.ts): which operations a",
    "// token issued with `client` reaches; the hub refuses the rest with 403.",
    "export {",
    "  CLIENT_TOKEN_PROFILE_NAMES,",
    "  CLIENT_TOKEN_PROFILES,",
    "  type ClientTokenProfile,",
    '} from "@agency_hub_core/contracts";',
    "",
    "export function createClient(options: KernelClientOptions): KernelClient {",
    "  return createKernelClient(kernelOperations, options);",
    "}",
    "",
  ].join("\n");

  const packageJson = `${JSON.stringify(
    {
      name: "@kernel/sdk",
      version: input.sdkVersion,
      description: "Generated kernel API client. Do not edit by hand — regenerate with `pnpm contracts:generate`.",
      type: "module",
      exports: { ".": "./src/index.ts" },
      dependencies: {
        "@agency_hub_core/contracts": "workspace:*",
        "zod": "^4.1.5",
      },
    },
    null,
    2,
  )}\n`;

  const readme = [
    "<!-- Generated by `pnpm contracts:generate`. Do not edit by hand. -->",
    "",
    "# @kernel/sdk",
    "",
    "Generated, typed client for the kernel API. Every operation is named after",
    "its `routeSchemas` key; request/response types and runtime validation come",
    "straight from the Zod contracts, so this package cannot drift from what the",
    "server enforces.",
    "",
    "```ts",
    'import { createClient } from "@kernel/sdk";',
    "",
    'const client = createClient({ baseUrl: "", auth: { mode: "cookie" } });',
    'const me = await client.me();                       // typed + runtime-validated',
    'const revenue = await client.pageRevenue({ params: { pageLabel: "lana" }, query: { period: "7d" } });',
    "```",
    "",
    "## How the SDK is versioned and pinned (DP 10, owner-confirmed)",
    "",
    "Distribution is **git-tag installs** — no npm registry:",
    "",
    "```jsonc",
    '// consumer package.json',
    '"@kernel/sdk": "github:<org>/core#sdk-vX.Y.Z"',
    "```",
    "",
    "- `KERNEL_CONTRACT_HASH` (in `meta.ts`) is a sha256 over the normalized",
    "  OpenAPI document. Consumer CI compares its pinned hash against",
    "  core@main's published hash; a mismatch is contract drift and fails the",
    "  build.",
    "- `sdk-vX.Y.Z` tags are published by the core release step; a scheduled",
    "  bump-PR updates each consumer's pin.",
    "- Everything in this package is machine-generated. Fix things in",
    "  `packages/contracts` (runtime: `src/sdk-runtime.ts`; generator:",
    "  `src/generate-sdk.ts`) and regenerate.",
    "",
  ].join("\n");

  return new Map([
    ["package.json", packageJson],
    ["README.md", readme],
    ["src/operations.ts", operationsTs],
    ["src/meta.ts", metaTs],
    ["src/index.ts", indexTs],
  ]);
}
