import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import openapiTS, { astToString } from "openapi-typescript";

import { createLogger } from "@agency_hub_core/shared";

import { buildApiServer } from "../../../apps/runtime/src/api/server.ts";

async function main() {
  const encryptionKey = Buffer.alloc(32, 0);
  const server = await buildApiServer({
    config: {
      databaseUrl: "",
      encryptionKey,
      encryptionKeyVersion: 1,
      encryptionKeysByVersion: new Map([[1, encryptionKey]]),
      logLevel: "silent",
      apiHost: "0.0.0.0",
      apiPort: 3000,
      trustProxy: false,
      sessionTtlDays: 30,
      fanslyBaseUrl: "https://apiv3.fansly.com/api/v1",
      onlyMonsterBaseUrl: "https://omapi.onlymonster.ai",
      syncHttpTraceFile: null,
      fanslyDefaultDelayMs: 2500,
      fanslyDmConversationsDelayMs: 5000,
      fanslyDmMessagesDelayMs: 7500,
      followerPageDelayMs: 5000,
      onlyFansDefaultDelayMs: 1000,
      transactionLookbackDays: 7,
      transactionRescanCapDays: 30,
      syncSharedRateLimitEnabled: false,
      syncPageExecutorConcurrency: 1,
      syncObservabilityRetentionDays: 30,
      healthSyncLightMaxAgeMinutes: 180,
      healthSyncFollowerMaxAgeMinutes: 1080,
      telegramBotToken: null,
      telegramChatId: null,
      telegramEnabled: false,
      telegramReportHourUtc: 9,
    },
    logger: createLogger("silent"),
    pool: {} as never,
    db: {} as never,
    adapter: {} as never,
    onlyFansAdapter: {} as never,
    async close() {},
  });

  try {
    await server.ready();
    const spec = server.swagger() as unknown as Record<string, unknown>;
    const openapiPath = path.resolve("reference/agency-hub.openapi.json");
    const typesPath = path.resolve("packages/contracts/src/generated/api-types.ts");

    await mkdir(path.dirname(typesPath), { recursive: true });
    await writeFile(openapiPath, `${JSON.stringify(spec, null, 2)}\n`, "utf8");

    const ast = await openapiTS(spec as any);
    const generated = [
      "// Generated by `pnpm contracts:generate`.",
      "",
      astToString(ast),
      "",
    ].join("\n");
    await writeFile(typesPath, generated, "utf8");
  } finally {
    await server.close();
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
