-- WP-F1 stream vocabulary: `stats_snapshot`, the account-level time-series
-- sweep (profile/media traffic, the earnings mix, tracking links, the discovery
-- tag counters, and the three mass-DM broadcast routes + /polls + /recapstats
-- that A28-5 rides on this lane rather than on a `dm_commerce` stream of their
-- own).
--
-- DDL ONLY, and its own file, for two reasons that are both load-bearing:
--
-- 1. `ALTER TYPE ... ADD VALUE` is fine inside a per-file transaction on
--    PG >= 12, but the new value cannot be USED by a row insert in the same
--    transaction (the 0060/0120 precedent). Keeping the enum alone in its file
--    makes that impossible by construction.
-- 2. §3.3's ordering rule: enum values may land early, but a stream enters the
--    TS-side SYNC_STREAMS/PLATFORM_STREAMS unions only in the slice that ships
--    its handler, gate, seed-pause, rollup exemption, monitor entry and gate
--    registration. Enum-first, TS-last.
--
-- The other five streams the plan names (notifications, catalog, media_stats,
-- post_replies, payouts) are DELIBERATELY not added here: each arrives with the
-- package that ships its handler, so an enum value can never name a lane that
-- would throw "Unsupported executor stream" on dispatch.

ALTER TYPE "sync_stream" ADD VALUE IF NOT EXISTS 'stats_snapshot';
