-- WP-F5 stream vocabulary: `post_replies`, the comment archive walk.
--
-- The lane that reads `GET /post/{postId}/replies` over the whole post
-- back-catalogue and stores full comment bodies. It exists at all because of
-- [E1]: every observed `/replies` GET in the 2026-08-19 capture was preceded
-- ~40 ms by `POST /api/v1/postreply/verify` with the same post id (5/5), and
-- until a bare GET was proven to work server-side this whole package was
-- contingent. **[E1] PASSED (A25, 2026-08-22): the bare GET returns the
-- comments with no preceding POST.** The kernel therefore NEVER issues that
-- POST — §1 excludes write-shaped calls to the platform, and a test greps the
-- adapter to keep it that way.
--
-- DDL ONLY, and its own file, for the two reasons 0131/0133/0135 state:
--
-- 1. `ALTER TYPE ... ADD VALUE` is fine inside a per-file transaction on
--    PG >= 12, but the new value cannot be USED by a row insert in the same
--    transaction (the 0060/0120 precedent). Keeping the enum alone in its file
--    makes that impossible by construction.
-- 2. §3.3's ordering rule: enum values may land early, but a stream enters the
--    TS-side SYNC_STREAMS/PLATFORM_STREAMS unions only in the slice that ships
--    its handler, gate, seed-pause, rollup exemption, monitor entry and gate
--    registration. Enum-first, TS-last.
--
-- The remaining planned streams (media_stats, payouts) are DELIBERATELY not
-- added here: each arrives with the package that ships its handler, so an enum
-- value can never name a lane that would throw "Unsupported executor stream"
-- on dispatch, fleet-wide.

ALTER TYPE "sync_stream" ADD VALUE IF NOT EXISTS 'post_replies';
