#!/usr/bin/env node
// Vendor the shared ChatGoose hotkey scheme (packages/chatgoose-hotkeys) into a
// client as a compiled, dependency-free `@chatgoose/hotkeys` package — the same
// contract as scripts/vendor-sdk.mjs: compile HERE with core's tsc, ship js +
// d.ts, stamp a manifest the client's tests verify. Hotkeys deliberately do NOT
// ride the SDK vendor: the SDK is re-vendored only from the deployed core, and a
// hotkey change must not drag undeployed contracts into a client.
//
// Usage: node scripts/vendor-hotkeys.mjs <target-dir> [--allow-dirty]
//   e.g. node scripts/vendor-hotkeys.mjs ../fansly-chat/vendor/chatgoose-hotkeys
//        node scripts/vendor-hotkeys.mjs ../onlyfans-chat/packages/chatgoose-hotkeys
//        node scripts/vendor-hotkeys.mjs ../chat-extension/vendor/chatgoose-hotkeys
//
// ALL clients (fansly-chat, onlyfans-chat, chat-extension) must ship the same
// manifest sha256 from the same source commit.

import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import { cpSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const coreRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packageRoot = join(coreRoot, "packages/chatgoose-hotkeys");
const args = process.argv.slice(2);
const allowDirty = args.includes("--allow-dirty");
const targetArg = args.find((arg) => !arg.startsWith("--"));
if (!targetArg) {
  console.error("Usage: node scripts/vendor-hotkeys.mjs <target-dir> [--allow-dirty]");
  process.exit(1);
}
const target = resolve(process.cwd(), targetArg);

// Same provenance rule as vendor-sdk.mjs: the manifest's sourceCommit must
// reproduce these bytes, so a dirty tree is refused (or stamped "-dirty").
const dirtyTree = execSync("git status --porcelain", { cwd: coreRoot }).toString().trim();
if (dirtyTree && !allowDirty) {
  console.error(
    "vendor-hotkeys: refusing to vendor from a dirty tree — the manifest's sourceCommit would not reproduce these bytes.\n" +
      "Commit (or stash) the working tree first, or pass --allow-dirty to stamp the artifact as dirty.\n" +
      dirtyTree,
  );
  process.exit(1);
}
const headCommit = execSync("git rev-parse HEAD", { cwd: coreRoot }).toString().trim();
const sourceCommit = dirtyTree ? `${headCommit}-dirty` : headCommit;

const packageJson = JSON.parse(readFileSync(join(packageRoot, "package.json"), "utf8"));
const scheme = readFileSync(join(packageRoot, "src/scheme.ts"), "utf8");
const schemeVersion = Number(scheme.match(/HOTKEY_SCHEME_VERSION = (\d+)/)?.[1]);
if (!Number.isInteger(schemeVersion)) {
  console.error("HOTKEY_SCHEME_VERSION not found in packages/chatgoose-hotkeys/src/scheme.ts");
  process.exit(1);
}

// ── Stage: drop the `.ts` import extensions for bundler-resolution consumers ──
const staging = mkdtempSync(join(tmpdir(), "chatgoose-hotkeys-vendor-"));
mkdirSync(join(staging, "src"), { recursive: true });
for (const file of readdirSync(join(packageRoot, "src"))) {
  if (!file.endsWith(".ts")) continue;
  const content = readFileSync(join(packageRoot, "src", file), "utf8").replace(/(from\s+"\.[^"]*)\.ts"/g, '$1"');
  writeFileSync(join(staging, "src", file), content);
}
writeFileSync(join(staging, "tsconfig.json"), JSON.stringify({
  compilerOptions: {
    target: "ES2022",
    lib: ["ES2022"],
    module: "ESNext",
    moduleResolution: "bundler",
    types: [],
    strict: true,
    declaration: true,
    outDir: "dist",
    rootDir: "src",
    skipLibCheck: true,
    isolatedModules: true,
  },
  include: ["src"],
}, null, 2));
writeFileSync(join(staging, "package.json"), JSON.stringify({ name: "chatgoose-hotkeys-staging", type: "module" }, null, 2));

const tsc = join(dirname(createRequire(join(coreRoot, "package.json")).resolve("typescript/package.json")), "bin/tsc");
try {
  execSync(`node ${tsc} -p ${staging}`, { stdio: "inherit" });
} catch {
  console.error(`\nVendor compile failed — staged sources left at ${staging} for inspection`);
  process.exit(1);
}

// ── Ship ──
rmSync(join(target, "dist"), { recursive: true, force: true });
mkdirSync(target, { recursive: true });
cpSync(join(staging, "dist"), join(target, "dist"), { recursive: true });
rmSync(staging, { recursive: true, force: true });

writeFileSync(join(target, "package.json"), `${JSON.stringify({
  name: "@chatgoose/hotkeys",
  version: packageJson.version,
  private: true,
  description: "Vendored ChatGoose hotkey scheme (generated by core scripts/vendor-hotkeys.mjs — do not edit).",
  type: "module",
  exports: {
    ".": {
      types: "./dist/index.d.ts",
      default: "./dist/index.js",
    },
  },
}, null, 2)}\n`);
writeFileSync(join(target, "README.md"), [
  "# @chatgoose/hotkeys (vendored)",
  "",
  "Generated by core `scripts/vendor-hotkeys.mjs` from `packages/chatgoose-hotkeys` — do not edit.",
  "The spec (table, platform constraints, engine rules) is that package's README in the hub repo.",
  "Re-vendor into BOTH clients from the same clean hub commit; the manifest sha256 must match.",
  "",
].join("\n"));

function listFiles(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? listFiles(path) : [path];
  });
}
const files = {};
for (const path of listFiles(join(target, "dist")).sort()) {
  files[relative(target, path)] = createHash("sha256").update(readFileSync(path)).digest("hex");
}
const sha256 = createHash("sha256").update(JSON.stringify(files)).digest("hex");
writeFileSync(join(target, "chatgoose-hotkeys.vendor.json"), `${JSON.stringify({
  schemeVersion,
  sha256,
  sourceCommit,
  source: "core scripts/vendor-hotkeys.mjs",
  files,
}, null, 2)}\n`);

console.log(`vendored @chatgoose/hotkeys v${packageJson.version} (scheme ${schemeVersion}, sha256 ${sha256.slice(0, 12)}…) → ${target}`);
